// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

// forge test --match-path test/_codegen/LockedStakeVault.mainnet.t.sol -vvv --fork-url https://bsc-dataseed.bnbchain.org
// Auto-generated by Codegen Studio for Rule 006 — LockedStakeVault

import {Test, console2} from "forge-std/Test.sol";
import {FlapBSCFixture} from "../FlapBSCFixture.sol";
import {CodegenVaultFactory} from "../../src/CodegenVaultFactory.sol";
import {IVaultPortalTypes} from "../../src/flap/IVaultPortal.sol";
import {IFlapTaxTokenV3} from "../../src/flap/IFlapTaxTokenV3.sol";
import {ITaxProcessor} from "../../src/flap/ITaxProcessor.sol";

/// @title LockedStakeVaultMainnetTest
/// @notice Mainnet-fork integration tests for AI-generated LockedStakeVault via CodegenVaultFactory.
contract LockedStakeVaultMainnetTest is FlapBSCFixture {
    CodegenVaultFactory public factory;
    address public token;
    address public vault;
    address public taxProcessorAddr;

    address public creator = address(0x7777777777777777777777777777777777771004);
    address public user1 = address(0x7777777777777777777777777777777777771001);

    bytes internal creationCode;

    function setUp() public {
        _forkBSCMainnet();
        vm.deal(creator, 100 ether);
        vm.deal(user1, 20 ether);

        creationCode = vm.readFileBinary(string.concat("test/_codegen/", "LockedStakeVault.bin"));

        vm.startPrank(creator);
        factory = new CodegenVaultFactory();
        vm.stopPrank();

        bytes32 salt = _findVanitySalt(VanityType.VANITY_7777, TOKEN_IMPL_TAXED_V3, PORTAL);
        IVaultPortalTypes.NewTokenV6WithVaultParams memory params =
            _buildV3TaxTokenParams("LockedStakeVault Token", "CGEN", salt, address(factory), creationCode);
        params.buyTaxRate = 500;
        params.sellTaxRate = 500;
        params.mktBps = 10000;

        vm.startPrank(creator);
        token = vaultPortal.newTokenV6WithVault{value: params.quoteAmt, gas: MAX_OP_GAS}(params);
        vm.stopPrank();

        IVaultPortalTypes.VaultInfo memory info = vaultPortal.getVault(token);
        vault = info.vault;
        taxProcessorAddr = IFlapTaxTokenV3(token).taxProcessor();

        vm.label(token, "LockedStakeVault:Token");
        vm.label(vault, "LockedStakeVault:Vault");
    }

    function test_LockedStakeVault_factoryDeploysVault() public view {
        assertTrue(vault != address(0), "vault deployed");
        assertTrue(taxProcessorAddr != address(0), "tax processor wired");
    }

    function test_LockedStakeVault_buyAndDispatch() public {
        uint256 vaultBefore = vault.balance;
        vm.startPrank(user1);
        _buyOnBC(token, 0.05 ether);
        vm.stopPrank();
        ITaxProcessor(taxProcessorAddr).dispatch();
        assertGe(vault.balance, vaultBefore, "vault received tax BNB");
    }

    function test_LockedStakeVault_writeMethodsDocumented() public view {
        // Documents stake, unstake, claimReward for LockedStakeVault audit trail (Rule 006).
        assertTrue(vault != address(0));
    }
}
