// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

import {Script, console} from "forge-std/Script.sol";
import {CodegenVaultFactory} from "src/CodegenVaultFactory.sol";

/// @title DeployCodegenFactory (BNB mainnet)
/// @notice MAINNET DEPLOY IS GATED. The CodegenVaultFactory deploys arbitrary, UNAUDITED
///         AI-generated bytecode. Do NOT deploy this to mainnet unless:
///           1. The factory itself has been audited, AND
///           2. You enforce that every generated vault is independently audited before launch
///              (e.g. via an allowlist of bytecode hashes / a review gate off-chain).
///         To intentionally deploy, set the env var I_UNDERSTAND_CODEGEN_RISK=true.
///
/// @dev forge script script/mainnet/bnb/DeployCodegenFactory.s.sol:DeployCodegenFactory \
///      --rpc-url https://bsc-dataseed.bnbchain.org --broadcast --verify
contract DeployCodegenFactory is Script {
    function run() external {
        require(
            vm.envOr("I_UNDERSTAND_CODEGEN_RISK", false),
            "Mainnet codegen deploy is gated: set I_UNDERSTAND_CODEGEN_RISK=true after auditing."
        );
        vm.startBroadcast();
        CodegenVaultFactory factory = new CodegenVaultFactory();
        console.log("CodegenVaultFactory (mainnet) deployed at:", address(factory));
        vm.stopBroadcast();
    }
}
